version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: resume-backend
    ports:
      - "8000:8000"  # assuming backend runs on 8000
    env_file:
      - .env
    volumes:
      - ./src:/app/src

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: resume-frontend
    ports:
      - "8501:8501"  # streamlit frontend
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./src:/app/src
